### ISSUE TITLE
How to parser formatter?

### ISSUE THREAD

**Issue by pinanunes** [Tutuchan/morrisjs#1]
Thanks for this widget!
How to parse the formatter option? For example to display the values as %?

**Comment by Tutuchan** [comment]
Hi,

You have to use the `JS` function from the **htmlwidgets** package, like so:

``` r
morrisjs(list(LETTERS[1:3], c(10, 20, 30))) %>% 
  mjsDonut(options = list(formatter = htmlwidgets::JS("function (y) { return y+'%' }")))
```

**Comment by pinanunes** [comment]
Thanks!
Works perfectly. I'm not that experienced with html widgets, so missed that.

**Comment by Tutuchan** [comment]
No problem!
