### ISSUE TITLE
Missing charts in flexdashboard

### ISSUE THREAD

**Issue by ThoDuyNguyen** [Tutuchan/morrisjs#2]
I test the library with flexdashboard and it seems the library does not work fine: 
- The charts were not auto re-sized properly in RStudio Viewer
- There were missing charts. I supposed this could be related to layout problem. 

Here is my testing code (please click source code link to see the code)
http://rpubs.com/thonguyenduy/test-morrisjs-package

**Comment by Tutuchan** [comment]
Thanks for the report!

Can you try with the fix I just pushed ? It should work fine now.

**Comment by ThoDuyNguyen** [comment]
The new code has fixed the problem. 

The case is closed. 

Thank you for your work. 

Kind regards.
