### ISSUE TITLE
Shiny Use

### ISSUE THREAD

**Issue by lrmelt** [Tutuchan/morrisjs#3]
How do we use this with Shiny?

I am using this is server.R:
`output$paretoPlot <- renderMorrisjs({
          morrisjs(pareto) %>% mjsBar(options=list(xkey="Topic",ykeys="Volume",labels="Volume",xLabelMargin=0,gridTextSize=12))
        })`

and this in ui.R:
`morrisjsOutput("paretoPlot",width = '100%', height = '500px')`

However, it breaks everything on the page in Shiny, including independent visualizations, while only throwing this error:
`Warning in output$paretoPlot(...) :
  Ignoring explicitly provided widget ID "htmlwidget-3864daf754ba2712591c3d3db9deb6b5"; Shiny doesn't use them`

This visualization works outside of Shiny.

**Comment by Tutuchan** [comment]
Thanks for the report!

I am looking into this, I'll get back to you asap.

**Comment by Tutuchan** [comment]
I just pushed a fix, let me know if it works on your end.

**Comment by lrmelt** [comment]
That fixed it. Thanks!

**Comment by Tutuchan** [comment]
Great!

**Comment by Ibrokhimsadikov** [comment]
Hello,  I have a issue while I am plotting several donuts with Morris.js, it is not showing all the charts
I have similar to more charts that I need to display
 output$third <- renderMorrisjs({
     cool3<-insta%>%
       filter(department==input$dept)%>%
       group_by(add_to_cart_order)%>%
       summarize(count=n())
     morrisjs(cool3) %>% 
       mjsDonut(options=list(colors=RColorBrewer::brewer.pal(n=9, name = "Set1")))
     
     
   })
